### PR TITLE
Improve the function for dice calculating, it can both work on volume…

### PR DESCRIPTION
**Pull request by sunshineDrizzle**
… and surface.

### CODE REVIEW

**Comment by helloTC** [comment]
I tested your code, while when my image as numpy.array, set(image) will return an error 'unhashable type: numpy.ndarray'

**Comment by helloTC** [comment]
Besides, I guess use two variable of label instead of paired label will be better in case of mixing.
a list with two elements isn't eaiser for user to understand in contrast of two list represented as label of each image.
What's your opinion of it?

**Comment by helloTC** [comment]
If the raw surface data's shape as (163842,1,1), then set(data) will return an error.
I tried use set(data[:,0,0]), then it can be run. But time cost is too long.

**Comment by sunshineDrizzle** [comment]
If you want to calculate dice between two whole data (whole data: such as the whole brain voxels' image which includes one or more labels), you need to specify label_pair as a tuple. If the label_pair is None, ... More information is available in the function's docstring.

**Pull request closed without merging**
